services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: aprendendo-laravel-app
    container_name: aprendendo-laravel-app
    # Sincroniza todo o seu código local com o /var/www/html do container
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-laravel
    # Carrega variáveis de ambiente do .env (copie .env.example para .env e ajuste se necessário)
    env_file:
      - .env

  db:
    image: postgres:14
    container_name: aprendendo-laravel-db
    environment:
      POSTGRES_DB: db-laravel
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-laravel

networks:
  app-laravel:


volumes:
  pgdata:
